apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.kafka.replicas | int }}
  podManagementPolicy: {{ .Values.kafka.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.kafka.updateStrategy }}
    {{- if (eq "Recreate" .Values.kafka.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.kafka.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.kafka.rollingUpdatePartition }}
    {{- end }}
  serviceName: {{ include "kafka.fullname" . }}-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-kafka.yaml") . | sha256sum }}
      {{- if and .Values.kafka.metrics.enabled .Values.kafka.metrics.podAnnotations }}
      {{- toYaml .Values.kafka.metrics.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.kafka.podAnnotations }}
      {{- range $key, $value := .Values.kafka.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "kafka.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if and .Values.kafka.metrics.enabled .Values.kafka.metrics.podLabels }}
      {{- toYaml .Values.kafka.metrics.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.kafka.podLabels }}
      {{- range $key, $value := .Values.kafka.podLabels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
    {{- with .Values.kafka.priorityClassName }}
      priorityClassName: {{ . }}
    {{- end }}
    {{- with .Values.kafka.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.kafka.imagePullSecrets }}
      imagePullSecrets:
    {{- range .Values.kafka.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
    {{- end }}
      containers:
      - name: {{ include "kafka.fullname" . }}
        image: {{ .Values.kafka.image }}:{{ .Values.kafka.imageVersion | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.kafka.imagePullPolicy }}
        command:
          - /bin/bash
          - -c
          - |
            export POD_ORDINAL=${HOSTNAME##*-}
            export BROKER_ID=${POD_ORDINAL}
            export LOG_DIRS={{ include "kafka.fullpath" . }}
            # Ensure log directory exists (fsGroup in podSecurityContext handles permissions)
            mkdir -p "${LOG_DIRS}"
            # Disable GC logging to avoid permission issues with /opt/kafka/logs
            # Patch the startup script - override KAFKA_JVM_PERFORMANCE_OPTS construction
            cp /opt/kafka/bin/kafka-server-start.sh /tmp/kafka-server-start.sh
            # Find and comment out any line that adds -Xlog:gc to JVM_PERF_OPTS
            sed -i 's/.*-Xlog:gc.*/# GC logging disabled to avoid permission issues/' /tmp/kafka-server-start.sh
            # Also try to remove -Xlog:gc from any variable assignments or JVM args
            sed -i 's/-Xlog:gc[^ ]*//g' /tmp/kafka-server-start.sh
            sed -i 's/-Xlog:gc\*[^ ]*//g' /tmp/kafka-server-start.sh
            # Override KAFKA_JVM_PERFORMANCE_OPTS at the start of the script
            sed -i '1a export KAFKA_JVM_PERFORMANCE_OPTS=""' /tmp/kafka-server-start.sh
            # Ensure base_dir is set correctly for the patched script
            sed -i 's|^\(base_dir=.*\)|base_dir=/opt/kafka/bin|g' /tmp/kafka-server-start.sh
            # Fix any relative paths that depend on base_dir location
            sed -i "s|\$base_dir/kafka-run-class|/opt/kafka/bin/kafka-run-class|g" /tmp/kafka-server-start.sh
            chmod +x /tmp/kafka-server-start.sh
            # Disable GC logging via environment variable as well
            export KAFKA_JVM_PERFORMANCE_OPTS=""
            # Copy config to writable location and substitute variables
            cp /opt/kafka/config/server.properties /tmp/server.properties
            sed -i "s/\${POD_ORDINAL}/${POD_ORDINAL}/g" /tmp/server.properties
            sed -i "s/\${KAFKA_BROKER_ID}/${BROKER_ID}/g" /tmp/server.properties
            sed -i "s|\${KAFKA_ADVERTISED_LISTENERS}|PLAINTEXT://{{ include "kafka.fullname" . }}-${POD_ORDINAL}.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.kafka.client_port }},PLAINTEXT_INTERNAL://{{ include "kafka.fullname" . }}-${POD_ORDINAL}.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.kafka.internal_port }}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_LISTENERS}|{{ include "kafka.listeners" . }}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_LOG_DIRS}|${LOG_DIRS}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_NUM_PARTITIONS}|{{ .Values.kafka.configmap.num_partitions }}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}|{{ .Values.kafka.configmap.offsets_topic_replication_factor }}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}|{{ .Values.kafka.configmap.transaction_state_log_replication_factor }}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}|{{ .Values.kafka.configmap.transaction_state_log_min_isr }}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_LOG_RETENTION_HOURS}|{{ .Values.kafka.configmap.log_retention_hours }}|g" /tmp/server.properties
            sed -i "s|\${KAFKA_LOG_SEGMENT_BYTES}|{{ .Values.kafka.configmap.log_segment_bytes }}|g" /tmp/server.properties
            # Format storage for KRaft mode if needed
            {{- if not .Values.kafka.configmap.zookeeper_connect }}
            if [ ! -f "${LOG_DIRS}/meta.properties" ]; then
              echo "Formatting Kafka storage for KRaft mode..."
              CLUSTER_ID="{{ .Values.kafka.configmap.cluster_id }}"
              if [ -z "$CLUSTER_ID" ]; then
                # Generate cluster ID from release name (deterministic, same for all pods)
                CLUSTER_ID=$(echo -n "{{ .Release.Name }}-{{ .Release.Namespace }}" | sha256sum | cut -d' ' -f1 | cut -c1-16)
              fi
              /opt/kafka/bin/kafka-storage.sh format -t "$CLUSTER_ID" -c /tmp/server.properties --ignore-formatted
              echo "Storage formatted with cluster ID: $CLUSTER_ID for node ID: $BROKER_ID"
            else
              echo "Storage already formatted, skipping format step"
            fi
            {{- end }}
            # Start Kafka using patched script (GC logging disabled)
            /tmp/kafka-server-start.sh /tmp/server.properties
        env:
        - name: POD_ORDINAL
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_JVM_PERFORMANCE_OPTS
          value: ""
        ports:
        - name: client-port
          containerPort: {{ .Values.kafka.client_port | int }}
          protocol: TCP
        - name: internal-port
          containerPort: {{ .Values.kafka.internal_port | int }}
          protocol: TCP
        {{- if .Values.kafka.metrics.enabled }}
        - name: metrics
          containerPort: {{ .Values.kafka.metrics.port }}
          protocol: TCP
        {{- end }}
      {{- if .Values.kafka.startupProbe.enabled }}
        startupProbe:
          tcpSocket:
            port: client-port
          periodSeconds: {{ .Values.kafka.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.kafka.startupProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.kafka.startupProbe.failureThreshold }}
          successThreshold: {{ .Values.kafka.startupProbe.successThreshold }}
      {{- end }}
      {{- if .Values.kafka.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: client-port
          initialDelaySeconds: {{ .Values.kafka.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.kafka.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.kafka.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.kafka.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.kafka.livenessProbe.successThreshold }}
      {{- end }}
      {{- if .Values.kafka.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: client-port
          initialDelaySeconds: {{ .Values.kafka.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.kafka.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.kafka.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.kafka.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.kafka.readinessProbe.successThreshold }}
      {{- end }}
      {{- if .Values.kafka.resources }}
        {{- $resources := dict }}
        {{- if .Values.kafka.resources.limits }}
          {{- $limits := dict }}
          {{- if and .Values.kafka.resources.limits.cpu (ne .Values.kafka.resources.limits.cpu "") }}
            {{- $_ := set $limits "cpu" .Values.kafka.resources.limits.cpu }}
          {{- end }}
          {{- if and .Values.kafka.resources.limits.memory (ne .Values.kafka.resources.limits.memory "") }}
            {{- $_ := set $limits "memory" .Values.kafka.resources.limits.memory }}
          {{- end }}
          {{- if $limits }}
            {{- $_ := set $resources "limits" $limits }}
          {{- end }}
        {{- end }}
        {{- if .Values.kafka.resources.requests }}
          {{- $requests := dict }}
          {{- if and .Values.kafka.resources.requests.cpu (ne .Values.kafka.resources.requests.cpu "") }}
            {{- $_ := set $requests "cpu" .Values.kafka.resources.requests.cpu }}
          {{- end }}
          {{- if and .Values.kafka.resources.requests.memory (ne .Values.kafka.resources.requests.memory "") }}
            {{- $_ := set $requests "memory" .Values.kafka.resources.requests.memory }}
          {{- end }}
          {{- if $requests }}
            {{- $_ := set $resources "requests" $requests }}
          {{- end }}
        {{- end }}
        {{- if $resources }}
        resources:
{{ toYaml $resources | indent 10 }}
        {{- end }}
      {{- end }}
        volumeMounts:
        - name: {{ include "kafka.fullname" . }}-data
          mountPath: {{ include "kafka.fullpath" . }}
        {{- if .Values.kafka.configmap.enabled }}
        - name: {{ include "kafka.fullname" . }}-config
          mountPath: /opt/kafka/config
        {{- end }}
{{- if .Values.kafka.volumeMounts }}
{{ toYaml .Values.kafka.volumeMounts | indent 8 }}
{{- end }}
      {{- with .Values.kafka.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- if .Values.kafka.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.kafka.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: {{ include "kafka.fullname" . }}-data
      {{- if .Values.kafka.persistentVolumeClaim.dataPersistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "kafka.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.kafka.configmap.enabled }}
      - name: {{ include "kafka.fullname" . }}-config
        configMap:
          name: {{ include "kafka.fullname" . }}-config
          items:
          - key: server.properties
            path: server.properties
          {{- if .Values.kafka.configmap.configOverride }}
          - key: override.properties
            path: override.properties
          {{- end }}
      {{- end }}
{{- if .Values.kafka.volumes }}
{{ toYaml .Values.kafka.volumes | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
{{- if .Values.kafka.persistentVolumeClaim.enabled }}
  volumeClaimTemplates:
{{- if .Values.kafka.persistentVolumeClaim.dataPersistentVolume.enabled }}
  - metadata:
      name: {{ include "kafka.fullname" . }}-data
      labels:
        app.kubernetes.io/name: {{ include "kafka.name" . }}-data
        app.kubernetes.io/instance: {{ .Release.Name }}-data
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      accessModes:
    {{- range .Values.kafka.persistentVolumeClaim.dataPersistentVolume.accessModes }}
      - {{ . | quote }}
    {{- end }}
    {{- if .Values.kafka.persistentVolumeClaim.dataPersistentVolume.storageClassName }}
      storageClassName: {{ .Values.kafka.persistentVolumeClaim.dataPersistentVolume.storageClassName | quote }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.kafka.persistentVolumeClaim.dataPersistentVolume.storage | quote }}
{{- end }}
{{- end }}

