apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.kafka.client_port | int }}
    targetPort: client-port
    protocol: TCP
    name: client-port
  - port: {{ .Values.kafka.internal_port | int }}
    targetPort: internal-port
    protocol: TCP
    name: internal-port
  {{- if .Values.kafka.metrics.enabled }}
  - port: {{ .Values.kafka.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP

